version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    expose:
      - "9000"
    networks:
      - BaraSira

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    expose:
      - "80"
    networks:
      - BaraSira

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: BaraSira
      MYSQL_USER: BaraSira
      MYSQL_PASSWORD: BaraSira
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - BaraSira

  redis:
    image: redis:7-alpine
    networks:
      - BaraSira

networks:
  BaraSira:

volumes:
  dbdata:
  vendor:
