version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    expose:
      - "9000"
    networks:
      - barasira_nwk

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: barasira-nginx:local
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    expose:
      - "80"
    networks:
      - barasira_nwk

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: barasira
      MYSQL_USER: barasira
      MYSQL_PASSWORD: barasira
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - barasira_nwk

  redis:
    image: redis:7-alpine
    networks:
      - barasira_nwk

networks:
  barasira_nwk:

volumes:
  dbdata:
  vendor:
