sonar.projectKey=barasira
sonar.organization=ton-organisation

sonar.sources=app,routes,resources/js
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**
