version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - barasira

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    expose:
      - "80"
    networks:
      - barasira

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: barasira
      MYSQL_USER: barasira
      MYSQL_PASSWORD: barasira
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - barasira

  redis:
    image: redis:7-alpine
    networks:
      - barasira

networks:
  barasira:

volumes:
  dbdata:
