services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.http.routers.barasira.rule=Host(`barasira.com`)
      - traefik.http.services.barasira.loadbalancer.server.port=80

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: barasira
      MYSQL_USER: barasira
      MYSQL_PASSWORD: barasira
      MYSQL_ROOT_PASSWORD: root
