# docker-compose.prod.yuml
version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_DATABASE: barasira
      DB_USERNAME: barasira
      DB_PASSWORD: barasira
      REDIS_HOST: redis
    networks:
      - barasira

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    expose:
      - "80"
    networks:
      - barasira

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: barasira
      MYSQL_USER: barasira
      MYSQL_PASSWORD: barasira
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - barasira

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - barasira

networks:
  barasira:

volumes:
  dbdata:
