# docker/php/Dockerfile

FROM php:8.4-fpm AS barasira_php

WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git curl zip unzip supervisor \
    libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy app
COPY . .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Laravel optimizations
RUN php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache \
    && php artisan event:cache

# Permissions
RUN chown -R www-data:www-data storage bootstrap/cache

# Supervisor config
COPY ./docker/php/supervisor.conf /etc/supervisor/conf.d/supervisor.conf

CMD ["php-fpm"]
