# Dockerfile

FROM php:8.3-fpm AS barasira_php

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git curl zip unzip libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader \
    && php artisan optimize:clear

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

FROM nginx:stable-alpine AS barasira_nginx

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html
COPY --from=barasira_php /var/www/html /var/www/html
