# docker/php/Dockerfile

FROM php:8.4-fpm AS barasira_php

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git curl zip unzip supervisor \
    libpng-dev libonig-dev libxml2-dev libzip-dev \
    libicu-dev libssl-dev pkg-config \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath intl gd zip \
    && docker-php-ext-enable opcache \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Redis extension
RUN pecl install redis \
    && docker-php-ext-enable redis

WORKDIR /var/www/html

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy composer files first (cache optimization)
COPY composer.json composer.lock ./

# Copy full application
COPY . .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress


# Laravel optimizations (only works AFTER full copy)
RUN php artisan config:clear \
    && php artisan route:clear \
    && php artisan view:clear \
    && php artisan optimize

# Permissions
RUN chown -R www-data:www-data /var/www/html \
    && find storage -type d -exec chmod 775 {} \; \
    && find bootstrap/cache -type d -exec chmod 775 {} \;

# Supervisor config
COPY ./docker/php/supervisor.conf /etc/supervisor/conf.d/supervisor.conf

CMD ["php-fpm"]
