# docker/node/Dockerfile.dev

FROM node:20

WORKDIR /var/www/html

# 1. Copier uniquement les fichiers nécessaires à npm install
# 2. Installer les dépendances AVANT de copier tout le projet
COPY package*.json ./
RUN npm install

# 3. Copier le reste du projet
COPY . .

EXPOSE 5173

CMD ["sh", "-c", "npm run sass & npm run dev"]
