FROM node:20-alpine

WORKDIR /app

# Fix Rollup optional dependency bug
ENV npm_config_optional=false

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
