FROM node:18

WORKDIR /app

# Fix Rollup optional dependency bug
ENV ROLLUP_SKIP_NODEJS_NATIVE=true
ENV npm_config_optional=false

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
